# Generated by Django 2.1.5 on 2021-07-27 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['created'], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
    ]
